# Auto-generated configuration file
DATA_PATH = r"D:\Labber_Data\Jay\purcell_tmon\Rshield\temperature"

config_list = [
    {
        "name": "Q1",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 0, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6721.2632,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 4.0,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3627.34099,
            "qb_mixer": 3629.04099,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.01,
            "pi_gain_ge": 0.222088,
            "pi2_gain_ge": 0.109684,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 3416.783411,
            "qb_mixer_ef": 3416.783411,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.01,
            "pi_gain_ef": 0.077727,
            "pi2_gain_ef": 0.036649,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
            "drag_alpha": {"optimal_alpha": 0.4},
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 1000,
    },
    {
        "name": "Q2",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 2, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6740,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3620.80596,
            "qb_mixer": 3620.80596,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
    {
        "name": "Q3",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 0, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6812.176,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 16.995,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3127.97435,
            "qb_mixer": 3134.14435,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.01,
            "pi_gain_ge": 0.242188,
            "pi2_gain_ge": 0.118532,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 2907.38483,
            "qb_mixer_ef": 2908.004829,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.01,
            "pi_gain_ef": 0.092946,
            "pi2_gain_ef": 0.047631,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
            "drag_alpha": {"optimal_alpha": 0.451553},
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 200,
    },
    {
        "name": "Q4",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 0, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6885.9376,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3310.05204,
            "qb_mixer": 3311.83204,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.02,
            "pi_gain_ge": 0.390547,
            "pi2_gain_ge": 0.189919,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 3094.21422,
            "qb_mixer_ef": 3092.914224,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.189472,
            "pi2_gain_ef": 0.093753,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 100,
    },
]
