# Auto-generated configuration file
DATA_PATH = r"D:\Labber_Data\Jay\purcell_tmon\temperature"

config_list = [
    {
        "name": "Q1",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 2, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6720.4009,
            "res_length": 10,
            "res_gain_ge": 0.5,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3620.63506,
            "qb_mixer": 3620.625062,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.01,
            "pi_gain_ge": 0.691195,
            "pi2_gain_ge": 0.40945,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 3409.397119,
            "qb_mixer_ef": 3409.397119,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.03,
            "pi_gain_ef": 0.013905,
            "pi2_gain_ef": 0.00755,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
            "sigma": 0.01,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.49,
        "relax_delay": 100,
    },
    {
        "name": "Q2",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 2, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6743,
            "res_length": 10,
            "res_gain_ge": 0.9,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4029.170438,
            "qb_mixer": 4029.170438,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.01,
            "pi_gain_ge": 0.451744,
            "pi2_gain_ge": 0.283355,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 100,
    },
    {
        "name": "Q3",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 2, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6810.8901,
            "res_length": 10,
            "res_gain_ge": 0.5,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3127.67887,
            "qb_mixer": 3127.600198,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.159435,
            "pi2_gain_ge": 0.075459,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
            "sigma": 0.01,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 100,
    },
    {
        "name": "Q4",
        "ch": {"res_ch": 0, "qb_ch": 0, "qb_ch_ef": 2, "ro_ch": 0},
        "res": {
            "res_freq_ge": 6883.7547,
            "res_length": 10,
            "res_gain_ge": 0.7,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 3311.94,
            "qb_mixer": 3313.053269,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.347061,
            "pi2_gain_ge": 0.148747,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 3095.881349,
            "qb_mixer_ef": 3095.881349,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.01,
            "pi_gain_ef": 0.006318,
            "pi2_gain_ef": 0.003346,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 100,
    },
]
