DATA_PATH = r"D:\Labber_Data\Jay\purcell_tmon"


config_list = [
    ########## Q1 Config ###########
    {
        "name": "Q1",
        "ch": {
            "res_ch": 0,
            "qb_ch": 0,
            "qb_ch_ef": 2,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 6717,
            "res_length": 10,
            "res_gain_ge": 0.2,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4497,
            "qb_mixer": 4497,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
    ########## Q2 Config ###########
    {
        "name": "Q2",
        "ch": {
            "res_ch": 0,
            "qb_ch": 0,
            "qb_ch_ef": 2,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 6740,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4497,
            "qb_mixer": 4497,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
    ########## Q3 Config ###########
    {
        "name": "Q3",
        "ch": {
            "res_ch": 0,
            "qb_ch": 0,
            "qb_ch_ef": 2,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 6813,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4497,
            "qb_mixer": 4497,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
    ########## Q4 Config ###########
    {
        "name": "Q4",
        "ch": {
            "res_ch": 0,
            "qb_ch": 0,
            "qb_ch_ef": 2,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 6890,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4497,
            "qb_mixer": 4497,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma_ge": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "qb_freq_ef": 4000,
            "qb_mixer_ef": 4000,
            "qb_gain_ef": 0.1,
            "qb_phase_ef": 0,
            "sigma_ef": 0.05,
            "pi_gain_ef": 0.1,
            "pi2_gain_ef": 0.1,
            "qb_flat_top_length_ef": 0.1,
            "ramsey_freq": 2,
            "nqz_qb": 1,
            "nqz_qb_ef": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
]
